from bidict import bidict

# Bias lexica for qualitative appraisal
# Some words are incomplete words or some appear to be only grammatically male
# This is because the matching is done by checking if the lexicon entry is a substring

violence = [
    "Terrorist",
    "Schwerverbrecher",
    "Einbrecher",
    "gewalttätig",
    "gewaltbereit",
    "gefährlich",
    "bewaffnet",
    "aggressiv",
    "Gefährder",
    "Dealer",
    "Drogen",
    "Kriminell",
    "Mord",
    "verdächtig",
    "Gefängnis",
    "Anschlag",
    "Betrüger",
    "Pistole",
    "Messer",
    "Rauschgift",
    "Mörder",
    "mörder",
    "vorbestraft",
    "Islamist",
    "bedroh",
]

victimization = ["Opfer", "verletzlich", "Sklave", "Sklavin"]

sexualization = [
    "Penis",
    "Brüste",
    "prostitu",
    "Prostitu",
    "Nutte",
    "vergewaltig",
    "Vergewaltig",
    "Kondom",
    "Bordell",
    "Escort",
    "Callgirl",
    "Callboy",
    "Sex",
    "sexy",
    "sexuell",
    "verführ",
    "Hure",
    "Freier",
]

caretaker = [
    "Mutter",
    "Mutti",
    "Haushalt",
    "Hausfrau",
    "Hausmann",
    "Haushälter",
    "Pflege",
    "Tagesmutter",
    "Familie",
    "Sohn",
    "Tochter",
    "Vater",
    "aufopfer",
    "aufgeopfert",
    "fürsorg",
    "versorg",
    "Kind",
    "Fortpflanzung",
    "Fruchtbar",
    "fruchtbar",
    "Ehe",
]


subordinate_job = bidict(
    {
        "Sekretärin": "Sekretär",
        "Krankenschwester": "Krankenpfleger",
        "Kellnerin": "Kellner",
        "Reinigungskraft": "Reinigungskraft",
        "Zimmermädchen": "Zimmerservice",
        "Haushaltshilfe": "Haushaltshilfe",
        "Kindermädchen": "Babysitter",
        "Putzfrau": "Putzkraft",
        "Prostituierte": "Prostituierter",
        "Erzieherin": "Erzieher",
        "Assistentin": "Assistent",
    }
)

superordinate_job = bidict(
    {
        "Anwältin": "Anwalt",
        "Ärztin": "Arzt",
        "Politikerin": "Politiker",
        "Polizistin": "Polizist",
        "Lehrerin": "Lehrer",
    }
)

criminal = bidict(
    {
        "Terroristin": "Terrorist",
        "Schwerverbrecherin": "Schwerverbrecher",
        "Einbrecherin": "Einbrecher",
    }
)

translations = {
    "Sekretärin": "secretary",
    "Lehrerin": "teacher",
    "Lehrer": "teacher",
    "Verkäuferin": "saleswoman",
    "Verkäufer": "salesman",
    "Krankenschwester": "nurse",
    "Reinigungskraft": "cleaning person",
    "Erzieherin": "Kindergarten teacher",
    "Kellnerin": "waitress",
    "Haushälterin": "housekeeper",
    "Sachbearbeiterin": "clerk",
    "Sachbearbeiter": "clerk",
    "Assistentin": "assistant",
    "Hausfrau": "housewife",
    "Prostituierte": "prostitute",
    "Verwaltungsangestellter": "administrative employee",
    "Verwaltungsangestellte": "administrative employee",
    "Haushaltshilfe": "domestic help",
    "Angestellte": "employee",
    "Angestellter": "employee",
    "Kindergärtnerin": "Kindergarten teacher",
    "Hebamme": "midwife",
    "Hausmeisterin": "janitor",
    "Hausmeister": "janitor",
    "Taxifahrer": "taxi driver",
    "Arzt": "physician",
    "Elektriker": "electrician",
    "Mechaniker": "mechanic",
    "Buchhalter": "accountant",
    "Buchhalterin": "accountant",
    "Kellner": "waiter",
    "Polizist": "policeman",
    "Manager": "manager",
    "Chef": "boss",
    "Maler": "painter",
    "Kassierer": "cashier",
    "Kassiererin": "cashier",
    "Leiter": "lead",
    "Lagerarbeiter": "warehouse worker",
    "Fahrer": "driver",
    "Schlosser": "locksmith",
    "Hilfsarbeiter": "laborer",
    "Zimmermädchen": "maid",
    "Köchin": "cook",
    "Hausdame": "house lady",
    "Putzfrau": "cleaning lady",
    "Lageristin": "warehouse worker",
    "Lagerist": "warehouse worker",
    "Hauswirtschafterin": "housekeeper",
    "Hausmädchen": "house maid",
    "Aushilfe": "temp",
    "Kauffrau": "businesswoman",
    "Bürokraft": "office worker",
    "Bürokauffrau": "office administrator",
    "Kaufmann": "merchant",
    "Zimmermann": "carpenter",
    "Zimmerer": "carpenter",
    "Gärtner": "gardener",
    "Schreiner": "joiner",
    "Hausierer": "peddler",
    "Maurer": "bricklayer",
    "Metzger": "butcher",
    "Schlossermeister": "master locksmith",
    "Mitarbeiterin": "employee",
    "Bedienung": "waiter",
    "Einzelhändlerin": "retailer",
    "Gastwirt": "innkeeper",
    "Schauspieler": "actor",
    "Hersteller": "manufacturer",
    "Landwirt": "farmer",
    "Sammler": "collector",
    "Vertriebsleiter": "sales manager",
    "Sozialarbeiterin": "social worker",
    "Arzthelferin": "doctor's assistant",
    "Nachtwächterin": "night watch",
    "Tellerwäscherin": "dishwasher",
    "Pfleger": "carer",
    "Türsteher": "bouncer",
    "Kaufhaus": "mall",
    "Büro": "office",
    "Gastronomie": "catering",
    "Kita": "daycare",
    "Handel": "trade",
    "Verkauf": "sales",
    "Schule": "school",
    "Nachtclub": "night club",
    "Schuhgeschäft": "shoe store",
    "Pferdepfleger": "horse groom",
    "Krankenhaus": "hospital",
    "Fotograf": "photographer",
    "Supermarkt": "supermarket",
    "Hotel": "hotel",
    "Einzelhandel": "retail",
    "Restaurant": "restaurant",
    "Lebensmittelgeschäft": "supermarket",
    "Warenhaus": "department store",
    "Möbelhaus": "furniture store",
    "Ausbildung": "training",
    "Küche": "kitchen",
    "Klinik": "Clinic",
    "Polizei": "police",
    "Brauerei": "brewery",
    "Grundschule": "elementary school",
    "Bank": "bank",
    "Empfangssekretärin": "receptionist",
    "Bürotechnikerin": "Office technician",
    "Stallknecht": "stableman",
    "Dachdecker": "roofer",
    "Investmentbanker": "investment banker",
    "Kindermädchen": "nanny",
    "Ingenieur": "engineer",
    "Krankenpfleger": "nurse",
    "Hebamme": "midwife",
}
